# Generated by Django 5.2.17 on 2026-08-08 02:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("repository_ref", models.CharField(max_length=500)),
                (
                    "adapter",
                    models.CharField(
                        choices=[
                            ("C_CMAKE_CTEST", "C_CMAKE_CTEST"),
                            ("C_MAKE_CTEST", "C_MAKE_CTEST"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "policy",
                    models.JSONField(
                        default=dict,
                        help_text="MissionPolicy, serialized from the frozen schema.",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CREATED", "CREATED"),
                            ("AUTHORIZED", "AUTHORIZED"),
                            ("SNAPSHOTTED", "SNAPSHOTTED"),
                            ("VALIDATING", "VALIDATING"),
                            ("BASELINE", "BASELINE"),
                            ("TRIAGE", "TRIAGE"),
                            ("STRESS_TEST", "STRESS_TEST"),
                            ("CORRELATE", "CORRELATE"),
                            ("PATCH", "PATCH"),
                            ("VERIFY", "VERIFY"),
                            ("EXPORTING", "EXPORTING"),
                            ("PAUSED", "PAUSED"),
                            ("CANCELLING", "CANCELLING"),
                            ("VERIFIED", "VERIFIED"),
                            ("REJECTED", "REJECTED"),
                            ("HUMAN_REVIEW", "HUMAN_REVIEW"),
                            ("FAILED", "FAILED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="CREATED",
                        max_length=64,
                    ),
                ),
                (
                    "paused_from",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CREATED", "CREATED"),
                            ("AUTHORIZED", "AUTHORIZED"),
                            ("SNAPSHOTTED", "SNAPSHOTTED"),
                            ("VALIDATING", "VALIDATING"),
                            ("BASELINE", "BASELINE"),
                            ("TRIAGE", "TRIAGE"),
                            ("STRESS_TEST", "STRESS_TEST"),
                            ("CORRELATE", "CORRELATE"),
                            ("PATCH", "PATCH"),
                            ("VERIFY", "VERIFY"),
                            ("EXPORTING", "EXPORTING"),
                            ("PAUSED", "PAUSED"),
                            ("CANCELLING", "CANCELLING"),
                            ("VERIFIED", "VERIFIED"),
                            ("REJECTED", "REJECTED"),
                            ("HUMAN_REVIEW", "HUMAN_REVIEW"),
                            ("FAILED", "FAILED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        help_text="Set when the mission pauses, cleared when it resumes. NULL on a mission that is not paused; a PAUSED mission with NULL here can only abort.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "verification_started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When VERIFY first produced a record. Once set, the candidate set is closed: adding a candidate afterwards is generate-until-pass.",
                        null=True,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VERIFIED", "VERIFIED"),
                            ("REJECTED", "REJECTED"),
                            ("HUMAN_REVIEW_REQUIRED", "HUMAN_REVIEW_REQUIRED"),
                        ],
                        help_text="Derived from the whole candidate set, never from the last run.",
                        max_length=64,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "mission",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FuzzingReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("LIVE_CAMPAIGN", "LIVE_CAMPAIGN"),
                            ("REPLAYED_CORPUS", "REPLAYED_CORPUS"),
                            ("NOT_RUN", "NOT_RUN"),
                        ],
                        help_text="No default: a replayed corpus cannot be reported as a live run.",
                        max_length=64,
                    ),
                ),
                ("harness", models.CharField(max_length=200)),
                ("engine", models.CharField(default="libFuzzer", max_length=100)),
                ("runtime_seconds", models.FloatField(default=0.0)),
                ("executions", models.BigIntegerField(default=0)),
                ("crashes_found", models.PositiveIntegerField(default=0)),
                ("unique_crashes", models.PositiveIntegerField(default=0)),
                ("corpus_size", models.PositiveIntegerField(default=0)),
                ("sanitizers", models.JSONField(default=list)),
                (
                    "replay_source",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("recorded_at", models.DateTimeField()),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuzzing_reports",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "db_table": "fuzzing_report",
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HEAP_BUFFER_OVERFLOW", "HEAP_BUFFER_OVERFLOW"),
                            ("STACK_BUFFER_OVERFLOW", "STACK_BUFFER_OVERFLOW"),
                            ("GLOBAL_BUFFER_OVERFLOW", "GLOBAL_BUFFER_OVERFLOW"),
                            ("USE_AFTER_FREE", "USE_AFTER_FREE"),
                            ("DOUBLE_FREE", "DOUBLE_FREE"),
                            ("MEMORY_LEAK", "MEMORY_LEAK"),
                            ("UNDEFINED_BEHAVIOUR", "UNDEFINED_BEHAVIOUR"),
                            ("INTEGER_OVERFLOW", "INTEGER_OVERFLOW"),
                            ("NULL_DEREFERENCE", "NULL_DEREFERENCE"),
                            ("ASSERTION_FAILURE", "ASSERTION_FAILURE"),
                            ("TIMEOUT", "TIMEOUT"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "INFO"),
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "tool",
                    models.CharField(
                        choices=[
                            ("COMPILER_DIAGNOSTIC", "COMPILER_DIAGNOSTIC"),
                            ("ADDRESS_SANITIZER", "ADDRESS_SANITIZER"),
                            (
                                "UNDEFINED_BEHAVIOUR_SANITIZER",
                                "UNDEFINED_BEHAVIOUR_SANITIZER",
                            ),
                            ("LIBFUZZER", "LIBFUZZER"),
                            ("CTEST", "CTEST"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "discovery_method",
                    models.CharField(
                        choices=[
                            ("FUZZING_CAMPAIGN", "FUZZING_CAMPAIGN"),
                            ("DIRECT_HARNESS", "DIRECT_HARNESS"),
                            ("REPLAYED_REPRODUCER", "REPLAYED_REPRODUCER"),
                        ],
                        help_text="No default: only FUZZING_CAMPAIGN supports 'our fuzzer found it'.",
                        max_length=64,
                    ),
                ),
                (
                    "replay_source",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("file_path", models.CharField(max_length=1000)),
                ("line", models.PositiveIntegerField(blank=True, null=True)),
                ("function", models.CharField(blank=True, max_length=300, null=True)),
                ("fingerprint", models.CharField(max_length=128)),
                (
                    "reproducible",
                    models.BooleanField(
                        default=False,
                        help_text="True only when a minimized input replayed from a clean build.",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "sanitizer_report",
                    models.TextField(blank=True, default="", max_length=20000),
                ),
                (
                    "code_slice",
                    models.TextField(blank=True, default="", max_length=20000),
                ),
                ("detected_at", models.DateTimeField()),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "db_table": "finding",
                "ordering": ["detected_at"],
            },
        ),
        migrations.CreateModel(
            name="BaselineReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("configure_ok", models.BooleanField()),
                ("build_ok", models.BooleanField()),
                ("tests_total", models.PositiveIntegerField(default=0)),
                ("tests_passed", models.PositiveIntegerField(default=0)),
                ("tests_failed", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("adapter", models.CharField(max_length=100)),
                ("recorded_at", models.DateTimeField()),
                ("log_ref", models.JSONField(blank=True, null=True)),
                (
                    "mission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "db_table": "baseline_report",
            },
        ),
        migrations.CreateModel(
            name="Authorization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("statement", models.TextField(max_length=4000)),
                ("granted_by", models.CharField(max_length=200)),
                ("granted_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("repository_ref", models.CharField(max_length=500)),
                (
                    "snapshot_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "evidence_ref",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorizations",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "db_table": "authorization",
                "ordering": ["-granted_at"],
            },
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "sha256",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("kind", models.CharField(max_length=64)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "db_table": "artifact",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MissionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Gap-free per-mission ordinal, allocated under the mission row lock."
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MISSION_CREATED", "MISSION_CREATED"),
                            ("MISSION_AUTHORIZED", "MISSION_AUTHORIZED"),
                            ("SNAPSHOT_RECORDED", "SNAPSHOT_RECORDED"),
                            ("PREFLIGHT_COMPLETED", "PREFLIGHT_COMPLETED"),
                            ("STATE_CHANGED", "STATE_CHANGED"),
                            ("STAGE_STARTED", "STAGE_STARTED"),
                            ("STAGE_PROGRESS", "STAGE_PROGRESS"),
                            ("STAGE_COMPLETED", "STAGE_COMPLETED"),
                            ("BASELINE_RECORDED", "BASELINE_RECORDED"),
                            ("BASELINE_PASSED", "BASELINE_PASSED"),
                            ("BASELINE_FAILED", "BASELINE_FAILED"),
                            ("FINDING_RECORDED", "FINDING_RECORDED"),
                            ("REPRODUCER_RECORDED", "REPRODUCER_RECORDED"),
                            ("PATCH_CANDIDATE_RECORDED", "PATCH_CANDIDATE_RECORDED"),
                            ("PATCH_POLICY_EVALUATED", "PATCH_POLICY_EVALUATED"),
                            ("VERIFICATION_RECORDED", "VERIFICATION_RECORDED"),
                            ("MISSION_VERDICT_RECORDED", "MISSION_VERDICT_RECORDED"),
                            ("EVIDENCE_EXPORTED", "EVIDENCE_EXPORTED"),
                            ("RESOURCE_USAGE_SAMPLED", "RESOURCE_USAGE_SAMPLED"),
                            ("TEARDOWN_CONFIRMED", "TEARDOWN_CONFIRMED"),
                            ("POLICY_VIOLATION", "POLICY_VIOLATION"),
                            ("MISSION_PAUSED", "MISSION_PAUSED"),
                            ("MISSION_RESUMED", "MISSION_RESUMED"),
                            ("MISSION_CANCELLED", "MISSION_CANCELLED"),
                            ("MISSION_FAILED", "MISSION_FAILED"),
                            ("LOG", "LOG"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AUTHORIZE", "AUTHORIZE"),
                            ("INGEST", "INGEST"),
                            ("BASELINE", "BASELINE"),
                            ("ANALYZE", "ANALYZE"),
                            ("STRESS_TEST", "STRESS_TEST"),
                            ("CORRELATE", "CORRELATE"),
                            ("PATCH", "PATCH"),
                            ("VERIFY", "VERIFY"),
                            ("EXPORT_EVIDENCE", "EXPORT_EVIDENCE"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CREATED", "CREATED"),
                            ("AUTHORIZED", "AUTHORIZED"),
                            ("SNAPSHOTTED", "SNAPSHOTTED"),
                            ("VALIDATING", "VALIDATING"),
                            ("BASELINE", "BASELINE"),
                            ("TRIAGE", "TRIAGE"),
                            ("STRESS_TEST", "STRESS_TEST"),
                            ("CORRELATE", "CORRELATE"),
                            ("PATCH", "PATCH"),
                            ("VERIFY", "VERIFY"),
                            ("EXPORTING", "EXPORTING"),
                            ("PAUSED", "PAUSED"),
                            ("CANCELLING", "CANCELLING"),
                            ("VERIFIED", "VERIFIED"),
                            ("REJECTED", "REJECTED"),
                            ("HUMAN_REVIEW", "HUMAN_REVIEW"),
                            ("FAILED", "FAILED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RUNNING", "RUNNING"),
                            ("SUCCEEDED", "SUCCEEDED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="RUNNING",
                        max_length=64,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "INFO"),
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        default="INFO",
                        max_length=64,
                    ),
                ),
                ("message", models.CharField(max_length=1000)),
                ("payload", models.JSONField(default=dict)),
                ("evidence_refs", models.JSONField(default=list)),
                ("metrics", models.JSONField(default=dict)),
                ("trace_id", models.CharField(max_length=64)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "db_table": "mission_event",
                "ordering": ["mission_id", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="PatchCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("MODEL_GENERATED", "MODEL_GENERATED"),
                            ("OPERATOR_SUPPLIED", "OPERATOR_SUPPLIED"),
                        ],
                        help_text="Never inflated: an operator-written candidate is labelled as one.",
                        max_length=64,
                    ),
                ),
                (
                    "model_provenance",
                    models.JSONField(
                        blank=True,
                        help_text="ModelProvenance. Present only when provenance is MODEL_GENERATED.",
                        null=True,
                    ),
                ),
                ("diff", models.TextField(max_length=200000)),
                ("files_changed", models.PositiveIntegerField(default=0)),
                ("lines_changed", models.PositiveIntegerField(default=0)),
                (
                    "policy_status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "ACCEPTED"),
                            ("REJECTED_PATH_NOT_ALLOWED", "REJECTED_PATH_NOT_ALLOWED"),
                            ("REJECTED_TOO_MANY_FILES", "REJECTED_TOO_MANY_FILES"),
                            ("REJECTED_TOO_MANY_LINES", "REJECTED_TOO_MANY_LINES"),
                            ("REJECTED_MALFORMED_DIFF", "REJECTED_MALFORMED_DIFF"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "policy_detail",
                    models.CharField(blank=True, default="", max_length=2000),
                ),
                (
                    "rationale",
                    models.TextField(blank=True, default="", max_length=5000),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patch_candidates",
                        to="missions.finding",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patch_candidates",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "db_table": "patch_candidate",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Export",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("formats", models.JSONField(default=list)),
                ("artifact_refs", models.JSONField(default=list)),
                (
                    "isolation_mode",
                    models.CharField(
                        choices=[
                            ("ROOTLESS_CONTAINER", "ROOTLESS_CONTAINER"),
                            ("SUBPROCESS_JAIL", "SUBPROCESS_JAIL"),
                        ],
                        help_text="How the target was contained. No default (D-049): the stronger claim must never be made by omission.",
                        max_length=64,
                    ),
                ),
                ("generated_at", models.DateTimeField()),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="missions.mission",
                    ),
                ),
                (
                    "recommended_patch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The one diff we stand behind. Validated against the verification records by EvidenceBundle before the bundle is written.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommended_by_exports",
                        to="missions.patchcandidate",
                    ),
                ),
            ],
            options={
                "db_table": "export",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Reproducer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("minimized", models.BooleanField(default=False)),
                ("replay_attempts", models.PositiveIntegerField(default=0)),
                ("replay_successes", models.PositiveIntegerField(default=0)),
                ("test_command", models.CharField(max_length=1000)),
                ("artifact", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reproducers",
                        to="missions.finding",
                    ),
                ),
            ],
            options={
                "db_table": "reproducer",
            },
        ),
        migrations.CreateModel(
            name="ResourceSample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cpu_seconds", models.FloatField(default=0.0)),
                ("peak_memory_mb", models.FloatField(default=0.0)),
                ("wall_seconds", models.FloatField(default=0.0)),
                ("sandbox_count", models.PositiveIntegerField(default=0)),
                ("gpu_seconds", models.FloatField(default=0.0)),
                ("sampled_at", models.DateTimeField()),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_samples",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "db_table": "resource_sample",
                "ordering": ["sampled_at"],
            },
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("commit_sha", models.CharField(blank=True, max_length=64, null=True)),
                ("archive_sha256", models.CharField(max_length=64)),
                ("file_count", models.PositiveIntegerField(default=0)),
                ("bytes_total", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "db_table": "snapshot",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gates",
                    models.JSONField(
                        help_text="GateMatrix, serialized from the frozen schema."
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "VERIFIED"),
                            ("REJECTED", "REJECTED"),
                            ("HUMAN_REVIEW_REQUIRED", "HUMAN_REVIEW_REQUIRED"),
                        ],
                        max_length=64,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                (
                    "worktree_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("resource_usage", models.JSONField(blank=True, null=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="missions.mission",
                    ),
                ),
                (
                    "patch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="missions.patchcandidate",
                    ),
                ),
            ],
            options={
                "db_table": "verification_record",
                "ordering": ["started_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BASELINE", "Baseline"),
                            ("SANITIZER_BUILD", "Sanitizer Build"),
                            ("FUZZ", "Fuzz"),
                            ("MINIMIZE", "Minimize"),
                            ("CORRELATE", "Correlate"),
                            ("PATCH_GENERATE", "Patch Generate"),
                            ("VERIFY", "Verify"),
                            ("EXPORT", "Export"),
                            ("TEARDOWN", "Teardown"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("LEASED", "Leased"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("TIMED_OUT", "Timed Out"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=64,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Inputs. Never a secret, never a raw archive.",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        default=dict,
                        help_text="Summary the orchestrator reads to pick the next transition.",
                    ),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("max_attempts", models.PositiveSmallIntegerField(default=1)),
                ("run_after", models.DateTimeField()),
                (
                    "deadline_at",
                    models.DateTimeField(
                        help_text="Mandatory at enqueue, set from MissionPolicy. Hitting it is a result (TIMED_OUT), not a failure."
                    ),
                ),
                (
                    "lease_owner",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "db_table": "job",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["state", "run_after"], name="job_claim_idx"),
                    models.Index(fields=["lease_expires_at"], name="job_lease_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["mission", "fingerprint"], name="finding_fp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missionevent",
            index=models.Index(
                fields=["mission", "sequence"], name="event_mission_seq_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="missionevent",
            constraint=models.UniqueConstraint(
                fields=("mission", "sequence"), name="mission_event_sequence_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrecord",
            index=models.Index(
                fields=["mission", "verdict"], name="verification_verdict_idx"
            ),
        ),
    ]
