# Generated by Django 5.2.17 on 2026-08-10 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="export",
            name="isolation_mode",
            field=models.CharField(
                choices=[
                    ("ROOTLESS_CONTAINER", "ROOTLESS_CONTAINER"),
                    ("CONTAINER_NO_NETWORK", "CONTAINER_NO_NETWORK"),
                    ("SUBPROCESS_JAIL", "SUBPROCESS_JAIL"),
                ],
                help_text="How the target was contained. No default (D-049): the stronger claim must never be made by omission.",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="StageToolRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("AUTHORIZE", "AUTHORIZE"),
                            ("INGEST", "INGEST"),
                            ("BASELINE", "BASELINE"),
                            ("ANALYZE", "ANALYZE"),
                            ("STRESS_TEST", "STRESS_TEST"),
                            ("CORRELATE", "CORRELATE"),
                            ("PATCH", "PATCH"),
                            ("VERIFY", "VERIFY"),
                            ("EXPORT_EVIDENCE", "EXPORT_EVIDENCE"),
                        ],
                        max_length=64,
                    ),
                ),
                ("tool_name", models.CharField(max_length=200)),
                ("tool_version", models.CharField(max_length=200)),
                (
                    "image_digest",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("flags", models.JSONField(default=list)),
                ("artifact_refs", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_tool_runs",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "db_table": "stage_tool_run",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["mission", "stage"], name="stage_tool_mission_idx"
                    )
                ],
            },
        ),
    ]
