# Generated by Django 5.2.17 on 2026-08-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0002_alter_export_isolation_mode_stagetoolrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name="mission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("idempotency_key",),
                name="mission_idempotency_key_unique",
            ),
        ),
    ]
