# Generated by Django 5.2.17 on 2026-08-19 20:07
#
# SEC-42 (#176) / D-083 §4 / D-086: database-level unique constraints backing the
# two idempotency keys that previously relied on application-level checking alone —
# Job(mission, kind) (orchestrator.queue.ensure_jobs_enqueued) and
# Finding(mission, fingerprint) (orchestrator.findings.record_finding).
#
# Job's constraint is conditional (excludes kind="VERIFY"): VERIFY is a documented
# exception (architecture spec §2.3, orchestrator/verify_dispatch.py's own module
# docstring, D-067 §1) that fans out one Job row per policy-accepted PatchCandidate,
# not one per mission — see missions/models.py's Job.Meta comment for the full
# reasoning. Finding's constraint is unconditional; no equivalent exception exists
# for it.
#
# finding_fp_idx (a non-unique index over the same two columns as the new Finding
# constraint) is dropped in the same migration rather than left alongside it, since
# the unique index Postgres builds for the constraint already serves every query
# finding_fp_idx served.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0003_mission_idempotency_key"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="finding",
            name="finding_fp_idx",
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=("mission", "fingerprint"),
                name="finding_mission_fingerprint_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "VERIFY"), _negated=True),
                fields=("mission", "kind"),
                name="job_mission_kind_unique",
            ),
        ),
    ]
