# Generated by Django 5.2.17 on 2026-08-24 23:45
#
# #22, D-144: `JobKind.ANALYZE` (real static-analysis stage), `AnalyzerTool.SEMGREP`,
# and `DiscoveryMethod.STATIC_ANALYSIS` — see `contracts/enums.py` and
# `missions/models.py` for the reasoning. `choices=` metadata only: no new column, no
# new index, no new constraint, and no data migration — existing `job.kind`/
# `finding.tool`/`finding.discovery_method` rows are untouched. Django still wants a
# migration to record the change (`makemigrations --check` fails without one even
# though Postgres itself enforces no CHECK constraint from `choices=`), so this exists
# to keep that check green, not because the schema shape changed.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0005_finding_crash_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="discovery_method",
            field=models.CharField(
                choices=[
                    ("FUZZING_CAMPAIGN", "FUZZING_CAMPAIGN"),
                    ("DIRECT_HARNESS", "DIRECT_HARNESS"),
                    ("REPLAYED_REPRODUCER", "REPLAYED_REPRODUCER"),
                    ("STATIC_ANALYSIS", "STATIC_ANALYSIS"),
                ],
                help_text="No default: only FUZZING_CAMPAIGN supports 'our fuzzer found it'.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="tool",
            field=models.CharField(
                choices=[
                    ("COMPILER_DIAGNOSTIC", "COMPILER_DIAGNOSTIC"),
                    ("ADDRESS_SANITIZER", "ADDRESS_SANITIZER"),
                    ("UNDEFINED_BEHAVIOUR_SANITIZER", "UNDEFINED_BEHAVIOUR_SANITIZER"),
                    ("LIBFUZZER", "LIBFUZZER"),
                    ("CTEST", "CTEST"),
                    ("SEMGREP", "SEMGREP"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="kind",
            field=models.CharField(
                choices=[
                    ("BASELINE", "Baseline"),
                    ("SANITIZER_BUILD", "Sanitizer Build"),
                    ("ANALYZE", "Analyze"),
                    ("FUZZ", "Fuzz"),
                    ("MINIMIZE", "Minimize"),
                    ("CORRELATE", "Correlate"),
                    ("PATCH_GENERATE", "Patch Generate"),
                    ("VERIFY", "Verify"),
                    ("EXPORT", "Export"),
                    ("TEARDOWN", "Teardown"),
                ],
                max_length=64,
            ),
        ),
    ]
