[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = test_*.py
testpaths = contracts/tests api/tests
addopts = -q
asyncio_mode = auto
filterwarnings =
    error::DeprecationWarning:contracts.*
    error::DeprecationWarning:api.*
