#!/usr/bin/env bash
# Prove that server-sent events survive the nginx ingress.
#
# This is the regression test for the trap in D-013 and in
# infrastructure/compose/nginx/includes/sse.conf: nginx buffers proxied responses by
# default, so an event stream works against the ASGI server directly and silently dies
# behind the proxy. Testing SSE anywhere except through nginx tests nothing.
#
# It runs against a stub upstream (infrastructure/scripts/testing/sse-stub.py), not
# against Django, so it works before the control API exists and does not need the database
# afterwards. It exercises the REAL committed nginx configuration.
#
# Two cases run:
#   1. committed config          -> stream must arrive incrementally
#   2. same config + buffering ON -> stream must NOT arrive incrementally
# Case 2 exists so that a green case 1 means something. A test that cannot fail is not a
# test.
#
#   infrastructure/scripts/smoke-sse.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
NGINX_DIR="${REPO_ROOT}/infrastructure/compose/nginx"

NGINX_IMAGE="nginxinc/nginx-unprivileged@sha256:0c79d56aee561a1d81c63f00eee5fb5fe29279560cdc55e91425133104c7fbe6"
PYTHON_IMAGE="python@sha256:4766d8b510c428e595d74b9cc5bbb2fae8e26316fffb4adc89908d79aacd58a2"

NET="brahmadatta-sse-smoke"
STUB="brahmadatta-sse-stub"
PROXY="brahmadatta-sse-proxy"
HOST_PORT="${SSE_SMOKE_PORT:-18443}"
TMPDIR_LOCAL="$(mktemp -d)"

# shellcheck disable=SC2329  # invoked by the EXIT trap below, not called directly
cleanup() {
  docker rm -f "${PROXY}" "${STUB}" >/dev/null 2>&1 || true
  docker network rm "${NET}" >/dev/null 2>&1 || true
  rm -rf "${TMPDIR_LOCAL}"
}
trap cleanup EXIT

if [[ ! -f "${NGINX_DIR}/certs/server.crt" ]]; then
  "${REPO_ROOT}/infrastructure/scripts/gen-dev-certs.sh"
fi

# The buffering-ON override. Same file name, mounted over includes/sse.conf, so case 2
# differs from case 1 by exactly one directive.
cat > "${TMPDIR_LOCAL}/sse-buffered.conf" <<'EOF'
# DELIBERATELY WRONG. Generated by smoke-sse.sh to prove the test can fail.
include /etc/nginx/includes/proxy-headers.conf;
proxy_buffering    on;
proxy_read_timeout 3600s;
proxy_send_timeout 3600s;
EOF

docker network create "${NET}" >/dev/null

docker run -d --rm --name "${STUB}" \
  --network "${NET}" \
  --network-alias control-api \
  --network-alias command-center \
  --user 65534:65534 \
  -e SSE_STUB_INTERVAL=0.4 \
  -e SSE_STUB_EVENTS=12 \
  -v "${REPO_ROOT}/infrastructure/scripts/testing/sse-stub.py:/srv/sse-stub.py:ro" \
  "${PYTHON_IMAGE}" python3 /srv/sse-stub.py >/dev/null

start_proxy() {
  # `${@:+"$@"}` rather than a local array: `set -u` treats an empty array expansion as
  # unbound on bash 3.2, which is what ships with macOS.
  docker rm -f "${PROXY}" >/dev/null 2>&1 || true
  docker run -d --rm --name "${PROXY}" \
    --network "${NET}" \
    -p "127.0.0.1:${HOST_PORT}:8443" \
    -v "${NGINX_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro" \
    -v "${NGINX_DIR}/includes:/etc/nginx/includes:ro" \
    -v "${NGINX_DIR}/profile/admin-allow.conf:/etc/nginx/profile/admin.conf:ro" \
    -v "${NGINX_DIR}/conf.d.dev:/etc/nginx/conf.d:ro" \
    -v "${NGINX_DIR}/certs:/etc/nginx/certs:ro" \
    ${@:+"$@"} \
    "${NGINX_IMAGE}" >/dev/null

  for _ in $(seq 1 40); do
    if docker exec "${PROXY}" nginx -T >/dev/null 2>&1; then break; fi
    sleep 0.25
  done
  sleep 0.75
}

URL="https://127.0.0.1:${HOST_PORT}/api/v1/missions/00000000-0000-0000-0000-000000000000/events"
rc=0

echo "=== case 1: committed config (proxy_buffering off) — expect STREAMING"
start_proxy
python3 "${REPO_ROOT}/infrastructure/scripts/testing/sse-client.py" "${URL}" --expect streaming || rc=1

echo
echo "=== case 2: proxy_buffering ON — expect NOT STREAMING (proves the test can fail)"
start_proxy -v "${TMPDIR_LOCAL}/sse-buffered.conf:/etc/nginx/includes/sse.conf:ro"
python3 "${REPO_ROOT}/infrastructure/scripts/testing/sse-client.py" "${URL}" --expect buffered || rc=1

echo
if [[ ${rc} -eq 0 ]]; then
  echo "SSE smoke: PASS"
else
  echo "SSE smoke: FAIL"
fi
exit "${rc}"
