#!/usr/bin/env bash
# Prove that server-sent events survive the nginx ingress.
#
# This is the regression test for the trap in D-013 and in
# infrastructure/compose/nginx/includes/sse.conf: nginx buffers proxied responses by
# default, so an event stream works against the ASGI server directly and silently dies
# behind the proxy. Testing SSE anywhere except through nginx tests nothing.
#
# It runs against a stub upstream (infrastructure/scripts/testing/sse-stub.py), not
# against Django, so it works before the control API exists and does not need the database
# afterwards. It exercises the REAL committed nginx configuration.
#
# Four cases run. Two of them INJECT A VIOLATION and require the stream to break, because
# a check that cannot fail is not a check:
#
#   1. committed config, fast stream        -> must arrive incrementally
#   2. + proxy_buffering ON                 -> must NOT arrive incrementally
#   3. committed config, 20s idle mid-stream-> connection must survive the gap
#   4. + proxy_read_timeout 5s              -> nginx must drop the connection in the gap
#
# Cases 3 and 4 were added for #114. They test `proxy_read_timeout 3600s`, which was the
# untested half of the sse.conf comment block: it measures the gap between two reads from
# the upstream, so only an upstream that genuinely goes silent exercises it.
#
# Two things about cases 1 and 2 that are easy to get wrong, both established by
# measurement in docs/06-operations/72-sse-buffering-measurements.md:
#
#   HTTP VERSION. The buffering stall is HTTP/1.1 only. Over ALPN h2 there is no stall
#   with proxy_buffering on at all, and curl negotiates h2 by default over TLS. A probe
#   that does not pin HTTP/1.1 reports that a broken config is fine. Both probes used here
#   are HTTP/1.1 — sse-client.py because urllib speaks nothing else, sse-timing-probe.py
#   because it sets the ALPN list explicitly.
#
#   FRAME SIZE. The stall is a ~16 KB byte threshold, not "held until the response ends".
#   The stub's default ~200-byte frames stall completely; 16 KB frames do not stall at
#   all. Do not "simplify" the stub by making its frames bigger.
#
# It runs against a stub upstream (infrastructure/scripts/testing/sse-stub.py), not
# against Django, so it works before the control API exists and does not need the database
# afterwards. It exercises the REAL committed nginx configuration.
#
#   infrastructure/scripts/smoke-sse.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
NGINX_DIR="${REPO_ROOT}/infrastructure/compose/nginx"

NGINX_IMAGE="nginxinc/nginx-unprivileged@sha256:0c79d56aee561a1d81c63f00eee5fb5fe29279560cdc55e91425133104c7fbe6"
PYTHON_IMAGE="python@sha256:4766d8b510c428e595d74b9cc5bbb2fae8e26316fffb4adc89908d79aacd58a2"

NET="brahmadatta-sse-smoke"
STUB="brahmadatta-sse-stub"
PROXY="brahmadatta-sse-proxy"
HOST_PORT="${SSE_SMOKE_PORT:-18443}"
TMPDIR_LOCAL="$(mktemp -d)"

# shellcheck disable=SC2329  # invoked by the EXIT trap below, not called directly
cleanup() {
  docker rm -f "${PROXY}" "${STUB}" >/dev/null 2>&1 || true
  docker network rm "${NET}" >/dev/null 2>&1 || true
  rm -rf "${TMPDIR_LOCAL}"
}
trap cleanup EXIT

if [[ ! -f "${NGINX_DIR}/certs/server.crt" ]]; then
  "${REPO_ROOT}/infrastructure/scripts/gen-dev-certs.sh"
fi

# The buffering-ON override. Same file name, mounted over includes/sse.conf, so case 2
# differs from case 1 by exactly one directive.
cat > "${TMPDIR_LOCAL}/sse-buffered.conf" <<'EOF'
# DELIBERATELY WRONG. Generated by smoke-sse.sh to prove the test can fail.
include /etc/nginx/includes/proxy-headers.conf;
proxy_buffering    on;
proxy_read_timeout 3600s;
proxy_send_timeout 3600s;
EOF

# The read-timeout override for case 4. 5s is shorter than the stub's 20s silence, so if
# `proxy_read_timeout 3600s` is what keeps an idle stream alive, this must kill it.
cat > "${TMPDIR_LOCAL}/sse-short-timeout.conf" <<'EOF'
# DELIBERATELY WRONG. Generated by smoke-sse.sh to prove case 3 can fail.
include /etc/nginx/includes/proxy-headers.conf;
proxy_buffering    off;
proxy_cache        off;
gzip               off;
proxy_read_timeout 5s;
proxy_send_timeout 5s;
EOF

docker network create "${NET}" >/dev/null

# Restarted per case: cases 3 and 4 need an upstream that goes silent mid-stream, which
# the fast stream of cases 1 and 2 never does.
start_stub() {
  docker rm -f "${STUB}" >/dev/null 2>&1 || true
  docker run -d --rm --name "${STUB}" \
    --network "${NET}" \
    --network-alias control-api \
    --network-alias command-center \
    --user 65534:65534 \
    ${@:+"$@"} \
    -v "${REPO_ROOT}/infrastructure/scripts/testing/sse-stub.py:/srv/sse-stub.py:ro" \
    "${PYTHON_IMAGE}" python3 /srv/sse-stub.py >/dev/null
  sleep 0.5
}

start_proxy() {
  # `${@:+"$@"}` rather than a local array: `set -u` treats an empty array expansion as
  # unbound on bash 3.2, which is what ships with macOS.
  docker rm -f "${PROXY}" >/dev/null 2>&1 || true
  # D-088 (T0): conf.d.dev/ became templates.dev/ — mounted at /etc/nginx/templates so
  # the image's own envsubst entrypoint step renders it into /etc/nginx/conf.d before
  # nginx starts (the default `docker run` command here is plain `nginx`, so the
  # entrypoint.d scripts run as normal). The stub upstream (sse-stub.py) never checks
  # the Authorization header, so the exact token value does not matter to this test —
  # only that it substitutes into a syntactically valid config.
  docker run -d --rm --name "${PROXY}" \
    --network "${NET}" \
    -p "127.0.0.1:${HOST_PORT}:8443" \
    -e CONTROL_API_OPERATOR_TOKEN="smoke-sse-not-a-real-token-0123456789abcdef" \
    -e NGINX_ENVSUBST_FILTER="^CONTROL_API_OPERATOR_TOKEN$" \
    -v "${NGINX_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro" \
    -v "${NGINX_DIR}/includes:/etc/nginx/includes:ro" \
    -v "${NGINX_DIR}/profile/admin-allow.conf:/etc/nginx/profile/admin.conf:ro" \
    -v "${NGINX_DIR}/templates.dev:/etc/nginx/templates:ro" \
    -v "${NGINX_DIR}/certs:/etc/nginx/certs:ro" \
    ${@:+"$@"} \
    "${NGINX_IMAGE}" >/dev/null

  for _ in $(seq 1 40); do
    if docker exec "${PROXY}" nginx -T >/dev/null 2>&1; then break; fi
    sleep 0.25
  done
  sleep 0.75
}

URL="https://127.0.0.1:${HOST_PORT}/api/v1/missions/00000000-0000-0000-0000-000000000000/events"
PROBE="${REPO_ROOT}/infrastructure/scripts/testing/sse-timing-probe.py"
CLIENT="${REPO_ROOT}/infrastructure/scripts/testing/sse-client.py"
rc=0

FAST_STUB=(-e SSE_STUB_INTERVAL=0.4 -e SSE_STUB_EVENTS=12)
# 2 frames, then 20 seconds of silence, then the rest. 20s is comfortably longer than
# case 4's injected 5s timeout and comfortably shorter than the committed 3600s.
IDLE_STUB=(-e SSE_STUB_INTERVAL=0.4 -e SSE_STUB_EVENTS=6
           -e SSE_STUB_IDLE_AFTER=2 -e SSE_STUB_IDLE_SECONDS=20)

echo "=== case 1: committed config (proxy_buffering off) — expect STREAMING"
start_stub "${FAST_STUB[@]}"
start_proxy
python3 "${CLIENT}" "${URL}" --expect streaming || rc=1
python3 "${PROBE}" "${URL}" --expect streaming --duration 9 || rc=1

echo
echo "=== case 2: proxy_buffering ON — expect STALLED (proves case 1 can fail)"
start_stub "${FAST_STUB[@]}"
start_proxy -v "${TMPDIR_LOCAL}/sse-buffered.conf:/etc/nginx/includes/sse.conf:ro"
python3 "${CLIENT}" "${URL}" --expect buffered || rc=1
python3 "${PROBE}" "${URL}" --expect stalled --duration 9 || rc=1

echo
echo "=== case 3: committed config, upstream silent for 20s — expect the stream to SURVIVE"
start_stub "${IDLE_STUB[@]}"
start_proxy
python3 "${PROBE}" "${URL}" --expect survives-idle --idle-starts-at 1.0 --duration 26 || rc=1

echo
echo "=== case 4: proxy_read_timeout 5s — expect DROPPED (proves case 3 can fail)"
start_stub "${IDLE_STUB[@]}"
start_proxy -v "${TMPDIR_LOCAL}/sse-short-timeout.conf:/etc/nginx/includes/sse.conf:ro"
python3 "${PROBE}" "${URL}" --expect dropped-by-idle --drop-before 12 --duration 26 || rc=1

echo
if [[ ${rc} -eq 0 ]]; then
  echo "SSE smoke: PASS"
else
  echo "SSE smoke: FAIL"
fi
exit "${rc}"
